#                                                     ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥
#                                                   ğŸ’»Resolute Items ConfigğŸ’»
#                                                   ğŸ”¥Coded By Mike3132ğŸ”¥
#                                                   ğŸ’»Resolute Items ConfigğŸ’»
#                                                     ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥

Version: 'Version 1.0'
ConfigVersion: '1.0'
##### WARNING: DO NOT CHANGE ANYTHING ABOVE THIS LINE IT WILL BREAK THE PLUGIN!#####

#âœâœâœâœâœPermissionsâœâœâœâœâœ



#â™¢â™¢â™¢â™¢â™¢Sun Talisman Itemsâ™¢â™¢â™¢â™¢â™¢

#Sun Talisman Name -> Name of the talisman item (Please use & for color codes).
Sun-Talisman-Name: '&eTalisman of the sun'

#Sun Talisman Lore -> Any lore lines you would like on the Sun Talisman (Please use & for color codes).
Sun-Talisman-Lore:
  - '&5A relic of an ancient civilization'
  - '&5It radiates light and heat'
  - ''
  - '&7"Keep your face to the sun and you'
  - '&7Will never see the shadows" - Helen Keller'

#Talisman of Poseidon Name -> Name of the talisman item (Please use & for color codes).
Poseidon-Talisman-Name: '&bTalisman of Poseidon'

#Talisman of Poseidon Lore -> Any lore lines you would like on the Sun Talisman (Please use & for color codes).
Poseidon-Talisman-Lore:
  - '&5It''s weighted heavily, covered'
  - '&5in barnacles and living coral'
  - ''
  - '&7"She loves the serene brutality of the ocean,'
  - '&7loves the electric power she felt with each breath'
  - '&7of we briny air" -Holly Black, Tithe'






#See messages.yml for all configurable plugin messages
#â™ If you have any questions please join my discord, open a support ticket and @Mike3132
#â™ https://discord.gg/ePQGvQuzG3
#â™ Thanks for downloading and have a wonderful day

#â™›â™›â™›â™›â™› END OF CONFIG â™›â™›â™›â™›â™›
#This is the default config file.